// packages/sdk/src/history.ts
import * as fs from "fs";
import * as path from "path";

/**
 * Interface defining what we save in the history record.
 * 定义历史记录中保存的数据结构。
 */
export interface HistoryEntry {
  /**
   * The original raw intent from the user.
   * 用户原始的意图文本。
   */
  intent: string;

  /**
   * The compiled .pos (YAML) content.
   * 编译后的 .pos YAML 内容。
   */
  compiledPos: string;

  /**
   * Timestamp of generation (ms).
   * 生成时的时间戳。
   */
  timestamp: number;

  /**
   * The model used for generation (e.g., "gpt-4o").
   * 用于生成的模型名称。
   */
  model: string;
}

/**
 * Saves the compiled prompt to a local history file in Markdown format.
 * 将编译后的 Prompt 保存为本地 Markdown 格式的历史记录文件。
 *
 * @param projectRoot The root path of the current project/workspace.
 * @param entry The history entry data.
 * @returns The full path to the saved file.
 */
export async function saveToHistory(
  projectRoot: string,
  entry: HistoryEntry,
): Promise<string> {
  // Define the history directory: .promptos/history
  const historyDir = path.join(projectRoot, ".promptos", "history");

  // Ensure directory exists
  // 确保目录存在，如果不存在则递归创建
  if (!fs.existsSync(historyDir)) {
    await fs.promises.mkdir(historyDir, { recursive: true });
  }

  // Generate a filename: YYYY-MM-DDTHH-mm-ss-slug.md
  // 生成文件名，包含时间戳和意图的简略摘要
  const date = new Date(entry.timestamp);

  // Format date parts manually to avoid locale issues in filenames
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  const hh = String(date.getHours()).padStart(2, "0");
  const min = String(date.getMinutes()).padStart(2, "0");
  const ss = String(date.getSeconds()).padStart(2, "0");

  const timeStr = `${yyyy}-${mm}-${dd}T${hh}-${min}-${ss}`;

  // Create a safe slug from the intent (take first 30 chars)
  // 从意图中截取前30个字符作为文件名的标识部分
  const slug = entry.intent
    .slice(0, 30)
    .trim()
    .replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, "_") // Replace non-alphanumeric chars with underscore (keep Chinese)
    .replace(/_+/g, "_"); // Merge multiple underscores

  const filename = `${timeStr}-${slug}.md`;
  const filePath = path.join(historyDir, filename);

  // Construct file content using Markdown Frontmatter
  // 构建文件内容：使用 Frontmatter 记录元数据，正文显示 YAML 代码块
  const fileContent = `---
timestamp: "${date.toISOString()}"
model: "${entry.model}"
intent: "${entry.intent.replace(/"/g, '\\"')}"
---

# Compiled PromptOS Definition

> Generated by PromptOS Compiler

\`\`\`yaml
${entry.compiledPos}
\`\`\`
`;

  // Write file to disk
  await fs.promises.writeFile(filePath, fileContent, "utf-8");

  return filePath;
}
