// packages/sdk/src/index.ts

import { SkillExporter } from "./compiler/skillExporter";
import { SkillPackage } from "./types";

export * from "./types";
export * from "./generatePrompt";
export * from "./compiler";
export * from "./history";
export * from "./compiler/skillExporter";

export async function exportToSkillStandard(
  abilityMeta: any,
  rawPrompt: string,
) {
  const compressed = SkillExporter.compressInstructions(rawPrompt);

  const skillPkg: SkillPackage = {
    meta: {
      name: abilityMeta.id,
      description: abilityMeta.description || "Generated by PromptOS",
    },
    instructions: compressed,
  };

  return {
    filename: "SKILL.md",
    content: SkillExporter.compileToMarkdown(skillPkg),
    directory: `.agent/skills/${abilityMeta.id}/`,
  };
}
